ACCEL_ASCII ""

(asciiHeader
  (asciiVersion 3 0)
  (timeStamp 2018 11 24 12 9 46)
  (program "Protel DXP" "Version 1.0.0.30000")
  (copyright "Copyright © Altium Limited 2015")
  (fileAuthor "")
  (headerString "")
  (fileUnits mil)
  (guidString "{00000000-0000-0000-0000-000000000000}")
)
(library "Library_1"
  (textStyleDef "(Default)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 91.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PartStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(WireStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PortStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "10pTIMESNEWROMAN"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "8pCOURIERNEWBOLD"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Courier New")
      (fontHeight 111.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 700)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (symbolDef "ECS-.327-12.5-34B_1_N"
    (originalName "ECS-.327-12.5-34B_1_N")
    (pin (pinNum 1)  (pt 300 -200) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 150 -200) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -200) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 600 -200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 750 -200) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 -200) "2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 300 0) (pt 300 -400) (width 10) )
    (line (pt 600 0) (pt 600 -400) (width 10) )
    (line (pt 400 0) (pt 400 -400) (width 10) )
    (line (pt 400 -400) (pt 500 -400) (width 10) )
    (line (pt 500 -400) (pt 500 0) (width 10) )
    (line (pt 500 0) (pt 400 0) (width 10) )
    (attr "RefDes" ""  (pt -50 50) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -50 -150) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "SPK0415HM4H-B-7_1_N"
    (originalName "SPK0415HM4H-B-7_1_N")
    (pin (pinNum 1)  (pt 300 0) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 0) "VDD" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 300 -100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -100) "2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -100) "SEL" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 300 -200) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -200) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -200) "CLK" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 300 -300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -300) "4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -300) "DATA" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt 1200 -300) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1350 -300) "5" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1200 -300) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt 1200 -200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1350 -200) "6" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1200 -200) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt 1200 -100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1350 -100) "7" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1200 -100) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt 1200 0) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1350 0) "8" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1200 0) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 300 100) (pt 300 -400) (width 10) )
    (line (pt 300 100) (pt 1200 100) (width 10) )
    (line (pt 300 -400) (pt 1200 -400) (width 10) )
    (line (pt 1200 -400) (pt 1200 100) (width 10) )
    (attr "RefDes" ""  (pt -50 50) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -50 -150) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "LTW-008ZDCG_1_N"
    (originalName "LTW-008ZDCG_1_N")
    (pin (pinNum 1)  (pt 200 -600) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 200 -750) "1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -600) "A" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 200 -500) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 200 -350) "2" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -500) "K" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (poly 
      (pt 100 -500)
      (pt 300 -500)
      (pt 200 -600)
    )
    (line (pt 100 -600) (pt 300 -600) (width 10) )
    (attr "RefDes" ""  (pt -50 50) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -50 -150) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "AS1130_BTST_1_N"
    (originalName "AS1130_BTST_1_N")
    (pin (pinNum 1)  (pt 1100 -1300) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -1300) "1" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1300) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 1100 -600) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -600) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -600) "CS6" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 300 -1300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -1300) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -1300) "VDD" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 1100 -700) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -700) "4" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -700) "CS7" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt 1100 -800) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -800) "5" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -800) "CS8" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt 1100 -900) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -900) "6" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -900) "CS9" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt 1100 -1400) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -1400) "7" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1400) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt 1100 -1100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -1100) "8" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1100) "CS11" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 9)  (pt 1100 -1000) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -1000) "9" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1000) "CS10" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 10)  (pt 300 -1400) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -1400) "10" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -1400) "VDD" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 11)  (pt 300 -500) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -500) "11" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -500) "IRQ" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 12)  (pt 300 -700) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -700) "12" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -700) "SYNC" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 13)  (pt 300 -300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -300) "13" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -300) "RSTN" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 14)  (pt 1100 -1500) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -1500) "14" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1500) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 15)  (pt 300 0) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 0) "15" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 0) "SCL" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 16)  (pt 300 -100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -100) "16" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -100) "SDA" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 17)  (pt 300 -900) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -900) "17" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -900) "ADDR" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 18)  (pt 300 -1500) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -1500) "18" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -1500) "VDD" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 19)  (pt 300 -1600) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -1600) "19" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -1600) "VDD" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 20)  (pt 1100 -500) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -500) "20" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -500) "CS5" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 21)  (pt 1100 -400) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -400) "21" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -400) "CS4" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 22)  (pt 1100 -1600) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -1600) "22" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1600) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 23)  (pt 1100 -200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -200) "23" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -200) "CS2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 24)  (pt 1100 -300) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -300) "24" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -300) "CS3" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 25)  (pt 1100 0) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 0) "25" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 0) "CS0" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 26)  (pt 300 -1700) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 150 -1700) "26" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -1700) "VDD" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 27)  (pt 1100 -100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -100) "27" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -100) "CS1" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 28)  (pt 1100 -1700) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1250 -1700) "28" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1700) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 300 -1800) (pt 300 100) (width 10) )
    (line (pt 300 -1800) (pt 1100 -1800) (width 10) )
    (line (pt 300 100) (pt 1100 100) (width 10) )
    (line (pt 1100 100) (pt 1100 -1800) (width 10) )
    (attr "RefDes" ""  (pt -50 50) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -50 -150) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "OVSRRGBCC3_1_N"
    (originalName "OVSRRGBCC3_1_N")
    (pin (pinNum 1)  (pt 500 -300) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 500 -150) "4" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 -300) "AN" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 200 -800) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 200 -950) "1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -800) "R" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 500 -800) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 500 -950) "2" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 -800) "G" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 800 -800) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 800 -950) "3" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 800 -800) "B" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (poly 
      (pt 100 -500)
      (pt 300 -500)
      (pt 200 -600)
    )
    (poly 
      (pt 400 -500)
      (pt 600 -500)
      (pt 500 -600)
    )
    (poly 
      (pt 700 -500)
      (pt 900 -500)
      (pt 800 -600)
    )
    (line (pt 100 -600) (pt 300 -600) (width 10) )
    (line (pt 400 -600) (pt 600 -600) (width 10) )
    (line (pt 700 -600) (pt 900 -600) (width 10) )
    (line (pt 200 -800) (pt 200 -600) (width 10) )
    (line (pt 500 -800) (pt 500 -600) (width 10) )
    (line (pt 800 -800) (pt 800 -600) (width 10) )
    (line (pt 500 -500) (pt 500 -300) (width 10) )
